---
title: "DE report"
author: "Sofia Illescas"
date: '2022-11-04'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(knitr)
library(RColorBrewer)
library(SummarizedExperiment)
library(geneplotter)
library(ggplot2)
library(devtools)
library(ggbiplot)
library(edgeR)
library(corpcor)  
library(M3C)
library(calibrate)
library(EnhancedVolcano) 
library(sva) 
library(pvclust) # Hierarchical clustering with p-values
library(dendextend) # fancy plotting dendrograms
library(caret)
library(psych)
library(sigclust2)
library(ggvenn)
```

```{r}

setwd("~/Vascular_Disease/MG-04_Illumina_totalRNASeq/preprocess/")


#Importing data as summarizedexperiment object
se <- readRDS("~/Vascular_Disease/MG-04_Illumina_totalRNASeq/preprocess/patients_and_controls")


# Quality assessment and normalization

## Preprocessing data
dge <- DGEList(counts = assays(se)$counts, genes = as.data.frame(mcols(se)), group = se$Case.Control)

# Computing counts per million
assays(se)$logCPM <- cpm(dge, log=TRUE, prior.count=0.5)




# Filtering lowly expressed genes
nsamples <- length(se$Process.ID)
sample_cutoff <- 0.2
nsamples_cutoff <- sample_cutoff*nsamples

logcpm_cutoff <- 1
mask <- rowSums(assays(se)$logCPM <= logcpm_cutoff) >= nsamples_cutoff

dim(se)
se.filt <- se[!mask, ]
dim(se.filt)
dge.filt <- dge[!mask, ]
dim(dge.filt)
kept_genes2b <- dim(se.filt)[1]

# Between sample normalization
dge.filt.norm <- calcNormFactors(dge.filt)
assays(se.filt)$logCPM.norm <- cpm(dge.filt.norm, log = TRUE, prior.count = 3, normalized.lib.sizes = TRUE)

saveRDS(se.filt, "~/Vascular_Disease/MG-04_Illumina_totalRNASeq/preprocess/se_filt")


# PCA based on normalized counts(normalized between samples)
pca_norm_pre <- prcomp(as.data.frame(t(assays(se.filt)$logCPM.norm)) , center=TRUE, scale=TRUE)
ggbiplot(pca_norm_pre, var.axes=FALSE, groups=se.filt$Case.Control, labels = colnames(se.filt)) + ggtitle("PCA based on normalized data and colored by type")

###################### DEAnalysis ############################################

##All controls vs all patients

# Without correcting for batch
se.filt$Case.Control <- relevel(factor(se.filt$Case.Control), ref="control")
mod <- model.matrix(~ se.filt$Case.Control, colData(se.filt))
mod0 <- model.matrix(~ 1, colData(se.filt))
pv <- f.pvalue(assays(se.filt)$logCPM.norm, mod, mod0)
sum(p.adjust(pv, method="fdr") < 0.05)

# Mean-variance relationship
FDRcutoff <- 0.05
v <- voom(dge.filt.norm, mod, plot = TRUE) # Voom is applied to the normalized and filtered DGEList object
fit <- lmFit(v, mod)
fit<- eBayes(fit)
res <- decideTests(fit, p.value = FDRcutoff)
summary(res)
# 1935 DE genes

# Add gene metadata (gene symbol) and fetch the table of results. Print first 15 sDEgenes
rowRanges(se.filt)
genesmd <- data.frame(symbol = rownames(res), stringsAsFactors = FALSE)
fit$genes <- genesmd
tt <- topTable(fit, coef = 2, n = Inf)
tt_sign <- tt[tt$adj.P.Val <= 0.05,]
head(tt_sign); nrow(tt_sign)
sum(tt$adj.P.Val < 0.05)
genes <- (tt$symbol[(tt$adj.P.Val < 0.05)])
genes_or <- genes[order(genes)]

pca_norm_post <- prcomp(as.data.frame(t(assays(se.filt)$logCPM.norm[genes,])) , center=TRUE, scale=TRUE)
ggbiplot(pca_norm_post, var.axes=FALSE, groups=se.filt$Summary.clinic) + ggtitle("PCA based on normalized data and colored by type")

## Venous controls vs venous patients
patients_v <- se.filt[,se.filt$Summary.clinic=="venous malformation"]
controls_v <- se.filt[,colnames(assay(se.filt))%in%c("HUVECS","HUVECs_2","HUVECs_3","HUVECs_4")]
se.v <- cbind(patients_v, controls_v)

se.v$Case.Control <- relevel(factor(se.v$Case.Control), ref="control")
mod <- model.matrix(~ se.v$Case.Control, colData(se.v))
mod0 <- model.matrix(~ 1, colData(se.v))
pv <- f.pvalue(assays(se.v)$logCPM.norm, mod, mod0)
sum(p.adjust(pv, method="fdr") < 0.05)


FDRcutoff <- 0.05
v <- voom(dge.filt.norm[,colnames(se.v)], mod, plot = TRUE) # Voom is applied to the normalized and filtered DGEList object
fit <- lmFit(v, mod)
fit<- eBayes(fit)
res <- decideTests(fit, p.value = FDRcutoff)
summary(res)

genesmd <- data.frame(symbol = rownames(res), stringsAsFactors = FALSE)
fit$genes <- genesmd
tt <- topTable(fit, coef = 2, n = Inf)
tt_sign <- tt[tt$adj.P.Val <= 0.05,]
head(tt_sign); nrow(tt_sign)
sum(tt$adj.P.Val < 0.05)
genes_v <- (tt$symbol[(tt$adj.P.Val < 0.05)])
genes_v_or <- genes[order(genes)]

#Venous PCA
pca_norm_v <- prcomp(as.data.frame(t(assays(se.v)$logCPM.norm[genes_v,])) , center=TRUE, scale=TRUE)
ggbiplot(pca_norm_v, var.axes=FALSE, groups=se.v$Case.Control, labels = colnames(se.v)) + ggtitle("PCA based on venous normalized data and colored by type")


## Lymphatic controls vs lymphatic patients
patients_l <- se.filt[,se.filt$Summary.clinic=="lymphatic malformation"]
controls_l <- se.filt[,colnames(assay(se.filt))%in%c("HDLECs_1", "HDLECs_2", "HDLECs_3")]
se.l <- cbind(patients_l, controls_l)

se.l$Case.Control <- relevel(factor(se.l$Case.Control), ref="control")
mod <- model.matrix(~ se.l$Case.Control, colData(se.l))
mod0 <- model.matrix(~ 1, colData(se.l))
pv <- f.pvalue(assays(se.l)$logCPM.norm, mod, mod0)
sum(p.adjust(pv, method="fdr") < 0.05)


FDRcutoff <- 0.05
v <- voom(dge.filt.norm[,colnames(se.l)], mod, plot = TRUE) # Voom is applied to the normalized and filtered DGEList object
fit <- lmFit(v, mod)
fit<- eBayes(fit)
res <- decideTests(fit, p.value = FDRcutoff)

genesmd <- data.frame(symbol = rownames(res), stringsAsFactors = FALSE)
fit$genes <- genesmd
tt <- topTable(fit, coef = 2, n = Inf)
tt_sign <- tt[tt$adj.P.Val <= 0.05,]
head(tt_sign); nrow(tt_sign)
sum(tt$adj.P.Val < 0.05)
genes_l <- (tt$symbol[(tt$adj.P.Val < 0.05)])
genes_l_or <- genes[order(genes)]

#Lymphatic PCA
pca_norm_l <- prcomp(as.data.frame(t(assays(se.l)$logCPM.norm[genes_l,])) , center=TRUE, scale=TRUE)
ggbiplot(pca_norm_l, var.axes=FALSE, groups=se.l$Case.Control, labels = colnames(se.l)) + ggtitle("PCA based on lymphatic normalized data and colored by type")


## Venous controls vs non-venous and non-lymphatic patients
patients <- se.filt[,se.filt$Case.Control=="case"]
patients_o <- patients[,patients$Summary.clinic!="lymphatic malformation"]
patients_o <- patients_o[,patients_o$Summary.clinic!="venous malformation"]
se.ov <- cbind(patients_o, controls_v)

se.ov$Case.Control <- relevel(factor(se.ov$Case.Control), ref="control")
mod <- model.matrix(~ se.ov$Case.Control, colData(se.ov))
mod0 <- model.matrix(~ 1, colData(se.ov))
pv <- f.pvalue(assays(se.ov)$logCPM.norm, mod, mod0)
sum(p.adjust(pv, method="fdr") < 0.05)

FDRcutoff <- 0.05
v <- voom(dge.filt.norm[,colnames(se.ov)], mod, plot = TRUE) # Voom is applied to the normalized and filtered DGEList object
fit <- lmFit(v, mod)
fit<- eBayes(fit)
res <- decideTests(fit, p.value = FDRcutoff)

genesmd <- data.frame(symbol = rownames(res), stringsAsFactors = FALSE)
fit$genes <- genesmd
tt <- topTable(fit, coef = 2, n = Inf)
tt_sign <- tt[tt$adj.P.Val <= 0.05,]
head(tt_sign); nrow(tt_sign)
sum(tt$adj.P.Val < 0.05)
genes_ov <- (tt$symbol[(tt$adj.P.Val < 0.05)])
genes_ov_or <- genes[order(genes)]

#Venous controls vs non-venous and non-lymphatic patients PCA
pca_norm_ov <- prcomp(as.data.frame(t(assays(se.ov)$logCPM.norm[genes_ov,])) , center=TRUE, scale=TRUE)
ggbiplot(pca_norm_ov, var.axes=FALSE, groups=se.ov$Summary.clinic) + ggtitle("PCA based on venous controls vs non-venous and non-lymphatic patients normalized data and colored by type")

#Lymphatic controls vs non-venous and non-lymphatic patients

se.ol <- cbind(patients_o, controls_l)
se.ol$Case.Control <- relevel(factor(se.ol$Case.Control), ref="control")
mod <- model.matrix(~ se.ol$Case.Control, colData(se.ol))
mod0 <- model.matrix(~ 1, colData(se.ol))
pv <- f.pvalue(assays(se.ol)$logCPM.norm, mod, mod0)
sum(p.adjust(pv, method="fdr") < 0.05)

FDRcutoff <- 0.05
v <- voom(dge.filt.norm[,colnames(se.ol)], mod, plot = TRUE) # Voom is applied to the normalized and filtered DGEList object
fit <- lmFit(v, mod)
fit<- eBayes(fit)
res <- decideTests(fit, p.value = FDRcutoff)

genesmd <- data.frame(symbol = rownames(res), stringsAsFactors = FALSE)
fit$genes <- genesmd
tt <- topTable(fit, coef = 2, n = Inf)
tt_sign <- tt[tt$adj.P.Val <= 0.05,]
head(tt_sign); nrow(tt_sign)
sum(tt$adj.P.Val < 0.05)
genes_ol <- (tt$symbol[(tt$adj.P.Val < 0.05)])
genes_ol_or <- genes[order(genes)]

pca_norm_ol <- prcomp(as.data.frame(t(assays(se.ol)$logCPM.norm[genes_ol,])) , center=TRUE, scale=TRUE)
ggbiplot(pca_norm_ol, var.axes=FALSE, groups=se.ol$Summary.clinic) + ggtitle("PCA based on lymphatic controls vs non-venous and non-lymphatic patients normalized data and colored by type")


genes_o <- intersect(genes_ov, genes_ol)
genes_no_all <- setdiff(genes_o, genes)
genes_no_all_v <- setdiff(genes_v, genes)
genes_no_all_l <- setdiff(genes_l, genes)

length(intersect(genes_ov, genes_v))
length(intersect(genes_ol, genes_l))

#Compare DE genes from the three groups
genes_lst <- list(genes_no_all_l, genes_no_all_v, genes_no_all)
names(genes_lst) <- c("lymphatic vs lymphatic", "venous vs venous", "'other' patients")
saveRDS(genes_lst, file="~/Vascular_Disease/MG-04_Illumina_totalRNASeq/preprocess/DEgenes")

#"#CD534CFF"
ggvenn(
  genes_lst, columns=names(genes_lst),
  fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF"),
  stroke_size = 0.5, set_name_size = 4, show_percentage = FALSE
)
```
